#!/usr/bin/env bash
# Brings up local dev with hot-reload, containerized:
#   1. Supabase local stack (database, Auth, API, mail catcher)     -> `supabase start`
#   2. Seed users (+ a few demo sales)                              -> scripts/seed-local.ts
#   3. The app with `next dev`, bind-mounted, in the foreground     -> docker compose up (Ctrl+C to stop)
# For programming with the app running directly on the host instead, use `bun run db:start` + `bun run dev`
# (docs/05-guias/setup-local.md). For testing the production image, use `bun run local:up`.
set -euo pipefail
cd "$(dirname "$0")/.."

say() { printf '\n\033[1m==> %s\033[0m\n' "$1"; }
die() { printf '\033[31m%s\033[0m\n' "$1" >&2; exit 1; }

command -v docker >/dev/null   || die "Docker is not installed."
docker info >/dev/null 2>&1    || die "Docker is not running. Start Docker Desktop and try again."
command -v supabase >/dev/null || die "Supabase CLI not found. Install it: brew install supabase/tap/supabase"
command -v bun >/dev/null      || die "Bun not found. Install it: https://bun.sh"

APP_PORT="${APP_PORT:-3000}"
if lsof -nP -iTCP:"$APP_PORT" -sTCP:LISTEN >/dev/null 2>&1 && ! docker ps --format '{{.Names}}' | grep -qx barstock_app_dev; then
    die "Port $APP_PORT is already in use by another process. Stop it or run: APP_PORT=3001 bun run local:dev"
fi

say "1/2 Supabase (database, Auth, API, Mailpit)"
supabase start >/dev/null 2>&1 || supabase start
eval "$(supabase status -o env)"
[ -n "${API_URL:-}" ] && [ -n "${ANON_KEY:-}" ] && [ -n "${SERVICE_ROLE_KEY:-}" ] || die "Could not read the Supabase configuration."

say "2/2 Seed users and demo data"
[ -d node_modules ] || bun install --frozen-lockfile
SUPABASE_URL="$API_URL" SUPABASE_ANON_KEY="$ANON_KEY" SUPABASE_SERVICE_ROLE_KEY="$SERVICE_ROLE_KEY" bun run scripts/seed-local.ts

# Inside the Docker network the app reaches the API gateway by container name (host.docker.internal is not needed).
# R2_* vars are NOT set here: docker-compose.r2.yml's MinIO container supplies them (dummy local credentials plus
# R2_ENDPOINT_OVERRIDE), so product/logo image upload works locally without real Cloudflare R2 credentials.
cat > .env.docker <<ENV
# Generated by scripts/local-dev.sh for docker-compose.yml + docker-compose.dev.yml + docker-compose.r2.yml.
# LOCAL demo keys of the Supabase CLI; never commit, never reuse elsewhere.
NEXT_PUBLIC_SUPABASE_URL=http://supabase_kong_barstock:8000
NEXT_PUBLIC_SUPABASE_ANON_KEY=$ANON_KEY
SUPABASE_SERVICE_ROLE_KEY=$SERVICE_ROLE_KEY
APP_URL=http://localhost:$APP_PORT
APP_PORT=$APP_PORT
ENV

say "App (hot-reload — edit and save, Ctrl+C to stop)"
echo "  Mailpit  ${MAILPIT_URL:-http://127.0.0.1:54324}   Studio  ${STUDIO_URL:-http://127.0.0.1:54323}   R2 (MinIO)  http://localhost:${R2_CONSOLE_PORT:-9001}"
echo "  Sign in (LOCAL ONLY, password ${LOCAL_USERS_PASSWORD:-barstock-local-2026}): admin@ · manager@ · cashier@barstock.local"
docker compose -f docker-compose.yml -f docker-compose.dev.yml -f docker-compose.r2.yml --env-file .env.docker up --build
